// Wordle — comprehensive 5-letter word list
// ANSWERS: curated common words that make good puzzles
// VALID_GUESSES: every accepted input (superset of ANSWERS)

const ANSWERS = [
  // A
  "abbey","abhor","abide","abode","abort","about","above","abuse","abyss","acorn",
  "acute","adage","adapt","adept","adieu","admit","adobe","adopt","adore","adult",
  "after","again","agate","agave","agent","agile","aging","aglow","agony","agree",
  "ahead","aisle","alarm","album","alert","algae","alike","align","allay","alley",
  "allot","allow","alloy","aloft","alone","along","aloof","aloud","alpha","altar",
  "alter","amaze","amber","amble","amend","amiss","among","ample","angel","anger",
  "angle","angry","anime","ankle","annex","annoy","antic","anvil","aorta","apart",
  "aphid","apple","apply","apron","aptly","arbor","ardor","arena","argue","arise",
  "aroma","arose","array","arrow","ashen","askew","aspen","assay","asset","atoll",
  "atone","attic","audio","audit","augur","avail","avian","avoid","awful","awoke",
  // B
  "bacon","badge","badly","bagel","baker","bandy","banjo","baron","basic","basil",
  "batch","bathe","bayou","beach","beard","beast","began","begin","below","beset",
  "bevel","bible","birch","bison","black","blade","blame","bland","blank","blaze",
  "bleat","bleed","bless","blimp","blind","bliss","blitz","block","blood","bloom",
  "blown","blunt","board","boost","booth","booty","borax","botch","bound","brace",
  "braid","brake","brand","brave","brash","brass","bread","break","breed","bride",
  "brine","brisk","brook","brood","broth","brown","brunt","brush","bulge","bully",
  "bumpy","bunch","bunny","burly","burnt","buyer","byway",
  // C
  "cabin","cacao","cache","camel","candy","canon","carat","cargo","carol","caste",
  "catch","cause","cedar","chain","chair","chalk","champ","chant","chaos","charm",
  "chart","chase","chasm","cheap","cheer","chess","chest","chide","chief","chill",
  "china","chirp","choir","chunk","cider","cigar","cinch","civic","claim","clamp",
  "clasp","clean","clear","cleft","clerk","cliff","climb","cling","cloak","clone",
  "cloth","cloud","clout","clove","clown","clump","cobra","cocoa","comet","comic",
  "comma","coral","couch","could","count","court","crack","craft","crane","crate",
  "crave","crawl","crazy","creak","creek","crest","crisp","crone","cross","crowd",
  "crown","crush","crust","cubic","curly","curse","cycle",
  // D
  "daddy","daily","dairy","daisy","dally","dance","dandy","debut","decoy","dense",
  "depot","depth","derby","devil","disco","divan","dodge","dowry","draft","drain",
  "drawl","drawn","dread","dream","dress","dried","drift","drill","drink","drive",
  "drone","drool","droop","drove","drown","dryer","duchy","dusky","dwarf","dwell",
  // E
  "eagle","early","earth","easel","ebony","eight","eject","elite","ember","emote",
  "empty","enact","endow","enjoy","entry","envoy","equal","error","ethic","evade",
  "event","every","exact","exert","exile","extra",
  // F
  "fable","facet","fairy","faith","false","fancy","fault","feast","feral","fetch",
  "field","fiery","filth","finch","first","fishy","fjord","flake","flame","flank",
  "flare","flask","flesh","flock","flood","floor","flora","fluid","fluke","focal",
  "focus","force","forge","forth","forum","found","foyer","frail","frame","frank",
  "fraud","fresh","frill","front","frost","froze","fruit","funny","fuzzy",
  // G
  "gavel","giddy","gland","glare","glass","gleam","glide","gloom","gloss","glyph",
  "golem","goofy","goose","grace","grade","graft","grain","grand","grant","grasp",
  "grass","grave","graze","greed","green","greet","grief","gripe","groan","groin",
  "grope","gross","grout","grove","gruel","gruff","grump","guava","guile","guise",
  "gulch","gusty",
  // H
  "hatch","haven","heart","hedge","heist","hence","hoist","holly","homer","honey",
  "horse","hotel","hound","house","human","humid","humor","hurry","hyena",
  // I
  "ideal","image","irate","irony",
  // J
  "joust","judge","juice","juicy","jumbo","junto",
  // K
  "karma","kayak","knack","kneel","knelt","knife","knock","knoll","known","koala",
  // L
  "label","lance","large","latch","later","layer","learn","leash","ledge","legal",
  "lemon","level","light","lilac","liner","lingo","liver","llama","local","lodge",
  "lofty","logic","loose","lorry","lucid","lucky","lunar","lusty","lyric",
  // M
  "magic","major","maker","manor","maple","march","marry","match","maxim","mayor",
  "mealy","meant","medal","mercy","merge","messy","metal","mimic","mirth","miser",
  "misty","model","mogul","moist","money","moose","moral","mourn","mousy","muddy",
  "mulch","mural","mound","mouse","mouth","music",
  // N
  "naive","nasal","nasty","naval","nerve","newly","night","noble","noise","north",
  "notch","novel","nudge","nurse","nymph",
  // O
  "occur","ocean","offer","olive","onion","onset","optic","orbit","order","other",
  "otter","outer","ovary","oxide","ozone",
  // P
  "paddy","paint","pansy","paper","parse","patch","patsy","pause","peach","pearl",
  "peppy","perch","peril","perky","petal","petty","phase","phone","piano","pilot",
  "pinch","pixel","pizza","place","plaid","plain","plank","plant","plaza","plead",
  "pleat","pluck","plumb","plume","plunk","plush","poker","polar","polka","posse",
  "pouch","pound","power","prank","prawn","preen","press","price","prick","pride",
  "prime","prior","prism","probe","prong","prone","prose","proud","prune","psalm",
  "pulse","punch","pupil","purge",
  // Q
  "quail","qualm","queen","query","quest","queue","quick","quiet","quota","quote",
  // R
  "rabbi","radar","rainy","raise","rally","ramen","ranch","range","rapid","raven",
  "reach","realm","reedy","regal","reign","relax","repay","repel","resin","retro",
  "ridge","rinse","ripen","risky","rival","rivet","robin","rocky","rodeo","rogue",
  "roost","rough","round","royal","ruddy","rugby","ruler","rusty",
  // S
  "saint","salsa","sauce","savvy","scale","scald","scalp","scene","scone","scoop",
  "scope","score","scout","scrub","sedan","serve","shade","shaft","shaky","shale",
  "shame","share","shark","sharp","shawl","sheen","shelf","shell","shift","shirt",
  "shoal","shore","short","shout","shrug","siege","sight","sixth","skate","skimp",
  "skull","skunk","slant","slate","slave","sleek","sleet","slick","slide","slime",
  "slink","slump","smack","small","smart","smear","smile","smite","smoke","snack",
  "snake","snare","snarl","sneak","sneer","snide","sniff","snout","solar","solid",
  "solve","sorry","sound","south","space","spare","spark","spasm","spawn","spear",
  "speck","speed","spend","spicy","spill","spine","spire","spite","spoke","spoof",
  "spook","sport","spout","sprig","spunk","squad","squat","squid","stain","stale",
  "stall","stand","spare","stare","stark","start","steam","steel","steep","steer",
  "stern","stiff","stake","stone","store","stout","stove","strap","straw","stuck",
  "study","stump","stung","style","suave","sugar","suite","sunny","super","swamp",
  "swear","sweet","swept","swift","swirl","sword","syrup",
  // T
  "taboo","talon","tapir","taste","taunt","tawny","teach","tense","their","theme",
  "thick","thief","thing","think","thorn","those","three","threw","throw","thumb",
  "thump","tiara","tiger","tight","timid","tipsy","titan","toast","toddy","token",
  "topaz","total","totem","trace","track","trade","trail","train","trait","tramp",
  "trash","trawl","triad","trial","tribe","trick","tried","troop","troth","trout",
  "trove","truce","truly","trump","trunk","truss","trust","tuber","tulip","tumor",
  "tunic","twang","tweak","twine","twirl","twist","tying",
  // U-V
  "ultra","uncut","undid","unify","unite","untie","until","unzip","upset","usher",
  "utter","vague","valid","valor","valve","vapor","vault","vaunt","verse","vicar",
  "vigor","viral","virus","visit","visor","vista","vivid","vixen","vocal","voice",
  "voila","vomit","voter","vouch","vowel","vying",
  // W-Z
  "waltz","waste","watch","waver","weary","weave","wedge","weedy","weird","welch",
  "whale","whack","whiff","while","whirl","wince","winch","wispy","witch","woken",
  "world","worse","wrath","wrist","wrong","wrote","yacht","yeast","yield","young",
  "yours","zebra","zesty","zilch","zonal",
];

// Valid guesses — accepts every answer plus hundreds of additional common words
const EXTRA_GUESSES = [
  // common words not in ANSWERS
  "aback","abase","abash","abate","abbot","abhor","abide","abode",
  "about","above","accel","ached","aches","acted","acute","adage",
  "adbot","added","adder","addle","adeem","added","affix","afoot",
  "afoul","after","again","agene","ageon","agets","agism","agist",
  "aglee","aglet","agley","agloo","agone","agood","agria","agrin",
  "agued","agues","aguni","aheap","ahimsa","ahull","aided","aider",
  "aired","airth","airts","aitch","aivers","aiyah","ajwan","alack",
  "alamo","alang","alans","alant","alary","alays","albas","alecs",
  "aleph","alert","algid","algin","algor","alkyd","allay","alloy",
  "allus","aloft","alone","along","aloof","aloud","altho","alula",
  "alums","alway","amaze","amber","amice","amigo","amino","amiss",
  "amity","amnio","amour","amped","ample","anear","angst","anile",
  "anima","anion","ankh","annal","annul","anoas","apian","araby",
  "areal","areas","areic","areola","ariel","ariel","arise","arked",
  "arles","armet","arnie","arpen","arras","arses","arson","artic",
  "arty","ascon","ashed","asker","aspic","aspis","assay","atilt",
  "atman","atony","atopy","atria","attic","audio","avian","avise",
  "aviso","awave","awful","axial","axile","axion","aztec",
  // B
  "babul","banco","banns","barmy","baron","basal","bases","basho",
  "bassi","basso","basts","bated","bates","baulk","bawdy","bayou",
  "bazar","beady","beamy","beano","bears","beefy","beery","begot",
  "belem","belie","bench","beryl","betas","betel","bevel","bicep",
  "bidet","bigot","bilge","billy","bimbo","bines","biome","biros",
  "bitch","bitty","blain","bland","blare","blase","blini","bloat",
  "bloke","bloomer","blots","blown","blowy","blurb","blurt","boded",
  "boggy","boned","boner","boney","bonny","booby","boded","boned",
  "booze","borax","boron","bossy","botch","bothy","bough","boxed",
  "brace","braid","braky","brawl","brawn","braze","breve","brief",
  "briny","briny","broil","bronx","brood","brown","brusk","bushy",
  "busin","busman","butch","butty","buzzy",
  // C
  "cabal","cadge","camel","cameo","caper","caput","carom","carry",
  "carte","caste","catty","cauls","cavil","cecum","cella","chair",
  "chalk","champ","chant","chaps","chard","chary","cheat","cheek",
  "chela","cheng","chyle","circa","cirri","clasp","clear","cleft",
  "cling","clump","coast","coign","combs","comus","conch","coney",
  "conge","corny","coset","coups","coven","cower","coyly","coypu",
  "cramp","craps","crass","creak","crept","crest","crick","crops",
  "cruse","crypt","cubby","cubit","cuddy","cured","curvy","cushy",
  "cutey","cycad",
  // D
  "daffy","dally","dandy","daunt","daven","decal","decry","delve",
  "demon","depot","depot","derby","desks","deter","detox","dingo",
  "dinky","diode","disco","ditsy","divvy","dizzy","dodgy","doggy",
  "doing","dolly","dopey","dotty","douse","dowdy","ducky","dumpy",
  "dungy","duped","dusky","dusty",
  // E
  "eager","earns","easel","eaten","edify","eerie","elder","elfin","enemy",
  "enjoy","epoxy","erode","erupt","essay","etude","evict",
  // F
  "faint","fancy","farce","farrago","fatty","fecal","fella","femur",
  "ferry","fetid","felon","fiend","fishy","fizzy","flair","flask",
  "fizzy","flaky","fleck","flinch","float","floppy","floss","flout",
  "flown","fluky","flunk","flung","flush","foamy","foggy","folly",
  "foray","frond","froth","froze","funky","fussy",
  // G
  "gamey","gassy","gauze","gauzy","gavel","gauzy","gawky","geeky",
  "germy","getup","girly","girth","gloat","glogg","gloom","gloss",
  "glove","gluey","gluey","gnome","golem","gorge","gouty","grapy",
  "graze","greedy","grimy","grody","groom","groat","groovy","grubs",
  "gruff","grump","grunge","guise","gutsy","gyrate",
  // H
  "habit","hacky","hairy","hammy","handy","harpy","harsh","hasty",
  "haute","haven","hazel","heady","heave","heavy","hedge","hefty",
  "herby","hertz","hippy","hoary","hobby","hokey","holler","hot",
  "hovel","hokey","hyena","hyper",
  // I
  "icier","icing","inane","incur","inept","inert","infer","inner",
  "inter","itchy","ivory","jazzy",
  // J
  "jaggy","jowly","joyous","jumpy","juror",
  // K
  "keyed","kitty","knave","kneel","knob","kneel",
  // L
  "lacey","laden","lairy","lanky","lardy","lapse","larva","later",
  "latte","leads","leaky","leery","lefty","leggy","liege","lithe",
  "liver","loamy","loopy","lossy","lousy","lowly","lumpy","lusty",
  // M
  "madly","mangy","manly","manly","massy","matey","mealy","meaty",
  "mince","minty","mirky","missy","misty","moldy","moldy","motif",
  "mousy","muddy","muggy","murky","mushy","musky","musty","myrrh",
  // N
  "nabob","nanny","narky","natty","naughty","needy","nerdy","nettle",
  "newsy","ninny","nippy","nobly","nifty","noisy","noisy","nubby",
  "nutty",
  // O
  "oaken","oauth","obese","odder","odeon","often","oleic","olive",
  "ombre","onset","orbit","organ","outro",
  // P
  "pack","paddy","pally","palmy","panty","papaw","patchy","patio",
  "patsy","paved","pearl","patio","penal","penny","perky","pervy",
  "petty","phage","piano","piney","pique","pithy","pixie","plait",
  "plasm","plump","plonk","plouk","podgy","pogey","polyp","poppy",
  "porky","potty","pouty","privy","primp","prone","proxy","pudgy",
  "puggy","punky","pursy","pushy","pygmy","pygmy",
  // Q
  "quaff","qualm","quark","quash","quiff","quirk","quoth",
  // R
  "rabid","rapsy","ratty","rawly","rebus","rebut","recur","reedy",
  "reeky","regal","remix","repro","rerun","retro","ridgy","risky",
  "ritzy","robin","rodeo","roguy","roomy","ropey","roomy","rowdy",
  "royal","ruddy","rugby","runty",
  // S
  "sable","sadhu","sadly","sag","sagas","salty","sandy","sappy",
  "saucy","savvy","scaly","scram","scrap","seamy","seedy","seize",
  "senile","septy","serum","shady","shaky","sharp","showy","shaggy",
  "siren","sissy","sixty","slain","slangy","soapy","sodden","soggy",
  "soppy","softy","soupy","sowth","sow","spasm","spicy","spiny",
  "splay","spout","spume","staid","stalky","staph","stash","starry",
  "stave","stays","steal","steep","stela","stoic","stomp","stony",
  "story","strap","stray","stupe","sudsy","sunny","surly","swami",
  "swash","swath","syrup",
  // T
  "tacit","tacky","taffy","taggy","taint","tammy","tangy","tanky",
  "tardy","tarot","tart","tasty","tatty","taupe","tarry","tawdry",
  "teary","teddy","teeny","tepid","terse","theta","thorny","thong",
  "timid","tippy","tithe","tipsy","toffy","tonal","tonic","toothy",
  "topsy","torte","tossy","total","touchy","trash","treed","treys",
  "tricky","trice","trite","troth","tryst","tubby","tumid","turbo",
  "turfy","tussy","tutti","twill","twine","tippy","tubby","turfy",
  // U
  "udder","ulcer","ulnar","umbra","unfit","unify","unmet","unpin",
  "unset","untie","unwed","unzip","urban","usurp",
  // V
  "vasty","vedic","venal","vexed","vicar","vigil","villa","virile",
  "vying",
  // W
  "wacky","wager","wagon","wally","warty","weedy","wiley","wily",
  "wingy","witty","wobbly","wonky","wordy","wormy","worse","worst",
  "woven","wrath","wreak","wreck","wring","write","wrong",
  // Additional common words
  "elbow","broke","blink","stink","clung","flung","slung","swung","brink",
  "drink","flint","glint","print","shrink","clink","slink","plonk","clonk",
  "front","frost","gloom","bloom","broom","groom","vroom","floss","cross",
  "gross","floss","atone","phone","stone","prone","ozone","clone","drone",
  "scone","alone","ozone","swore","shore","snore","store","score","spore",
  "adore","adore","ignore","crore",
  // X Y Z
  "yearn","yodel","yokel","yummy","zappy","zippy","zonal","zomby",
  // Additional common WORDLE-style words
  "abyss","afoot","aglow","agony","aloft","amend","among","angel",
  "antic","aorta","apron","arbor","arise","aroma","arson","ashen",
  "askew","atone","audio","audit","avail","bacon","badge","basil",
  "batch","bathe","bland","blaze","block","bloom","boost","brace",
  "braid","bland","brand","brave","brash","bread","bride","brine",
  "brook","brood","broth","brunt","brush","bulge","clamp","clean",
  "clear","cling","cloak","clone","cloth","cobra","count","court",
  "craft","crane","crave","crazy","crisp","croak","cross","crown",
  "crush","cubic","cycle","dance","debut","dense","depth","devil",
  "dread","dream","drift","drink","drove","eagle","earth","eight",
  "elite","ember","envoy","equal","evade","event","exile","extra",
  "facet","fairy","faith","feast","feral","fetch","field","flank",
  "flare","flesh","flock","flood","floor","fluid","focal","force",
  "forge","forth","forum","foyer","frail","frame","ahead","allay",
  "allow","alter","amaze","amber","anger","angle","angry","ankle",
  "annex","annoy","apart","apply","arbor","ardor","arena","argue",
  "greed","green","greet","grief","groan","groin","gross","grout",
  "grove","guile","guise","knack","kneel","knelt","knife","knock",
  "knoll","known","koala","lance","layer","learn","leash","ledge",
  "legal","lemon","level","light","lilac","liner","lingo","liver",
  "llama","local","lodge","lofty","logic","loose","lucky","lunar",
  "lyric","magic","major","maker","manor","maple","march","marry",
  "maxim","medal","mercy","metal","mimic","mirth","miser","model",
  "mogul","moist","moral","mourn","mulch","mural","nerve","night",
  "noble","noise","notch","novel","nudge","nurse","nymph","ocean",
  "onion","onset","optic","orbit","outer","paddy","pansy","paper",
  "pause","pearl","perch","peril","phase","pilot","pinch","pixel",
  "pizza","plaid","plain","plank","plant","plaza","plead","pleat",
  "plumb","plume","plunk","plush","poker","polar","polka","posse",
  "pouch","prank","prawn","preen","press","price","pride","prime",
  "prior","prism","probe","prong","prose","prune","pulse","punch",
  "pupil","purge","quail","queen","query","quest","quick","quiet",
  "quota","rabbi","radar","rainy","raise","rally","ranch","range",
  "rapid","raven","reach","realm","regal","reign","relax","repay",
  "repel","resin","ridge","rinse","ripen","risky","rival","rivet",
  "robin","rocky","rodeo","rogue","roost","rough","round","royal",
  "rugby","ruler","rusty","saint","salsa","sauce","savvy","scald",
  "scalp","scene","scone","scoop","scope","scout","sedan","serve",
  "shaft","shaky","shale","shark","sharp","shawl","sheen","shelf",
  "shell","shift","shirt","shoal","shore","short","shout","shrug",
  "siege","sight","sixth","skate","skimp","skull","skunk","slant",
  "slate","slave","sleek","sleet","slick","slide","slime","slink",
  "smack","small","smart","smear","smile","smite","smoke","snack",
  "snake","snare","snarl","sneak","sneer","snide","sniff","solar",
  "solid","solve","south","space","spark","spawn","spear","speck",
  "speed","spend","spicy","spill","spire","spite","spoke","spoof",
  "spook","sport","spout","sprig","spunk","squad","squat","squid",
  "stain","stall","stand","stark","start","steam","steel","steep",
  "steer","stern","stiff","stake","store","stout","stove","strap",
  "straw","stuck","study","stump","stung","style","suave","sugar",
  "suite","sunny","super","swamp","swear","sweet","swept","swift",
  "swirl","syrup","taboo","talon","taste","taunt","tawny","teach",
  "tense","theme","thick","thief","thing","thorn","those","threw",
  "tiara","tiger","tight","timid","tipsy","titan","toast","toddy",
  "token","topaz","totem","trace","track","trade","trail","train",
  "trait","tramp","trash","trawl","triad","trial","tribe","trick",
  "troop","troth","trout","trove","truce","truly","trump","trunk",
  "truss","trust","tuber","tulip","tumor","tunic","twang","tweak",
  "twine","twirl","twist","tying","ultra","uncut","undid","unify",
  "unite","untie","until","unzip","upset","usher","utter","vague",
  "valid","valor","valve","vapor","vault","vaunt","vigor","viral",
  "virus","visit","visor","vista","vivid","vixen","vocal","voice",
  "vomit","voter","vouch","vowel","waltz","waste","watch","waver",
  "weary","weave","wedge","weird","whale","whack","whiff","while",
  "whirl","wince","winch","wispy","witch","world","worse","wrath",
  "wrist","wrong","yacht","yeast","yield","young","zebra","zesty",
  // More common words for valid guesses
  "abaft","abash","abate","abbot","aloft","amble","angel","annul",
  "aspen","atoll","awful","awoke","axial","baggy","baker","bandy",
  "baron","basic","bayou","beard","beast","began","begin","beset",
  "bevel","bible","birch","bison","black","blade","blame","blank",
  "bleat","bleed","bless","blimp","blind","bliss","blitz","blown",
  "boggy","booty","brawn","brawl","brawny","birdy","bland","blaze",
  "clunk","chord","chair","chalk","champ","chant","chaos","charm",
  "chart","chase","chasm","cheap","cheer","chess","chest","chide",
  "chief","chill","china","chirp","cinch","civic","claim","clasp",
  "clear","cleft","clerk","cliff","climb","cock","clink","clown",
  "comet","comic","comma","canal","cable","chose","civil","class",
  "clean","cream","creak","creek","crimp","crest","drove","drawn",
  "drool","drone","draft","drain","drawl","eager","early","earth",
  "eight","eject","ember","emote","empty","enact","endow","enjoy",
  "entry","envoy","equal","error","ethic","evade","event","exact",
  "exert","exile","extra","flash","flair","flank","flame","flake",
  "float","floss","flout","flush","flounder","focal","foray","frank",
  "fraud","fresh","frost","glare","glass","gleam","glide","gloom",
  "gloss","gloat","gnash","golem","goofy","goose","grade","graft",
  "grain","grand","grant","grasp","grass","grave","graze","hatch",
  "haven","heart","hedge","heist","hence","hoist","holly","homer",
  "hotel","human","humid","humor","hurry","ideal","image","irony",
  "joust","judge","juice","juicy","jumbo","karma","kayak","latch",
  "lever","lover","lower","loyal","maker","manor","march","money",
  "mouse","mouth","music","match","patch","march","manor","maple",
  "merge","messy","metal","mimic","misty","model","mogul","moist",
  "naive","nasal","nasty","naval","nudge","offer","olive","orbit",
  "ought","outer","ovary","oxide","ozone","paint","pansy","paper",
  "parse","patsy","peach","peppy","perky","petal","petty","piano",
  "place","plain","plaid","plank","plant","plaza","plead","pleat",
  "pluck","plumb","plume","plunk","plush","polar","polka","posse",
  "pouch","power","preen","press","pride","prime","prior","prism",
  "probe","prong","prose","prune","psalm","pulse","punch","pupil",
  "quaff","qualm","quark","quash","raise","rural","ratel","retch",
  "rigor","rowdy","ruddy","realm","rapid","raven","reach","relay",
  "salsa","sauce","savvy","scald","scalp","scene","scone","scoop",
  "scope","score","scout","sedan","serve","shade","shaft","shaky",
  "shale","shame","share","shark","sharp","shawl","sheen","shelf",
  "shell","shift","shirt","shoal","shore","short","shout","shrug",
  "siege","sight","sixth","skate","skimp","skull","slant","slate",
  "slave","sleek","sleet","slick","slide","slime","slink","smack",
  "smart","smear","smile","smite","snack","snake","snare","snarl",
  "sneak","sneer","snide","sniff","solar","solid","solve","south",
  "space","spare","spark","spawn","spear","speck","speed","spend",
  "spill","spine","spire","spite","spoke","spoof","spook","sport",
  "spout","sprig","spunk","squad","squat","steel","steep","steer",
  "stern","stiff","stone","store","stout","stove","strap","straw",
  "stuck","study","stump","stung","style","sugar","suite","sunny",
  "swamp","swear","sweet","swept","swift","swirl","sword","syrup",
  "talon","taste","taunt","tawny","teach","tense","theme","thick",
  "thief","thing","think","thorn","those","throw","thumb","thump",
  "tiger","tight","tipsy","titan","toast","token","topaz","total",
  "totem","track","trade","trail","train","trait","tramp","trash",
  "trawl","triad","trial","tribe","trick","tried","troop","trout",
  "trove","truce","trump","trunk","truss","trust","tulip","tumor",
  "tunic","twang","tweak","twine","twirl","twist","ultra","uncut",
  "unify","unite","until","upset","usher","utter","valid","valor",
  "valve","vapor","vault","vigor","viral","virus","visit","visor",
  "vista","vivid","vocal","voice","vomit","voter","vouch","waltz",
  "waste","watch","waver","weary","weave","wedge","weird","whale",
  "whack","whiff","while","whirl","winch","wispy","witch","world",
  "wrath","wrist","wrong","yacht","yeast","yield","young","zebra",
];

// Build clean ANSWERS
const cleanAnswers = [...new Set(
  ANSWERS
    .map(w => w.toLowerCase().trim())
    .filter(w => /^[a-z]{5}$/.test(w))
)];

// Build VALID_GUESSES: all answers + extra guesses
const VALID_GUESSES = new Set(
  [...cleanAnswers,
   ...EXTRA_GUESSES
     .map(w => w.toLowerCase().trim())
     .filter(w => /^[a-z]{5}$/.test(w))
  ]
);
